### ISSUE TITLE
Random Game page returns Server Error (500) when there's no game in Plan to Play list.

### ISSUE THREAD

**Issue by hlischt** [Hexadigital/mygamelist#58]
https://remember.games/gamelist/random
This is a potential source of confusion: I initially thought it would return a random game from the entire catalog, not a random game from the PTP list.

**Comment by Hexadigital** [comment]
Good catch! That is indeed a bug as well as something that could use some clarification. It was a feature carried over from the old really-rough site, so to me it seemed more obvious than it actually is.
